version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stylelint-declaration-strict-value
    versions:
    - 1.7.10
    - 1.7.9
  - dependency-name: stylelint
    versions:
    - 13.12.0
  - dependency-name: stylelint-selector-tag-no-without-class
    versions:
    - 2.0.3
